### ISSUE TITLE
Adding Channels

### ISSUE THREAD

**Issue by matthewkulp** [holmesal/hashtag#12]
Attached are mock-ups.
1. Notice I got rid of the full width bar at the top of the app. This is because it serves a redundant function. It calls out the channel you are in, but so does the channel sidebar (by turning green when selected.) Channel view has to stay for functional purposes, so I got rid of the full-width bar.
2. Notice the add channel button is different than before. But now, it is wholly consistent (in fact, identical) to the channel screen on iOS.
3. The channel creation flow is identical to the iOS mock-ups, except in one key way: 
   I've done away with the the back button and instead placed a cancel button in the upper right. The philosophy.. the 'back' action makes the sense when a view is replaced by a new one and you are in a new location. In this case, with the whole app sliding and fading. The channel creation is less of a destination and more of an awakened process. It's process-ness calls for a 'Cancel' instead of a 'Back.'
   **Note: I did a mock-up where the whole channel column is replaced by the channel creation screen and gets a back button instead (because it's replacing the old view) for comparison.

![dt-add-alt](https://cloud.githubusercontent.com/assets/1914859/3884406/151624b8-21af-11e4-9f01-63701f25047f.png)
![dt-create 1](https://cloud.githubusercontent.com/assets/1914859/3884413/15409a4a-21af-11e4-847c-3fe9d5b629fd.png)
![dt-create 2](https://cloud.githubusercontent.com/assets/1914859/3884407/151e0f2a-21af-11e4-8a20-9bd0c7c00063.png)
![dt-create-3](https://cloud.githubusercontent.com/assets/1914859/3884409/152ba342-21af-11e4-936d-d0f7ffb03035.png)
![dt-join 1](https://cloud.githubusercontent.com/assets/1914859/3884410/152ece96-21af-11e4-927e-2a21de2659ed.png)
![dt-join 2](https://cloud.githubusercontent.com/assets/1914859/3884408/152ba716-21af-11e4-9bb0-97b74bc0f998.png)
![dt-join 3](https://cloud.githubusercontent.com/assets/1914859/3884411/152f1900-21af-11e4-990e-c245543bbfcf.png)
![dt-wall](https://cloud.githubusercontent.com/assets/1914859/3884412/153a8c9a-21af-11e4-9104-9dbfc74ae984.png)

**Comment by holmesal** [comment]
Based on our convo, I'm going to work on the text fields/etc while you work on the mocks for adding a channel in-line.

Questions to answer:
1. What happens to the channels you're currently in? How far down do they go?
2. How does this show/hide? (animation)

**Comment by holmesal** [comment]
This is mostly implemented in the latest release. A couple of caveats - 
1. I currently just move the existing channels down by a few hundred pixels.
2. There are currently no animations on show/hide.

Also, a bug I just noticed - 
Existing channels with no description are not hiding the description input.

**Comment by holmesal** [comment]
ping @matthewkulp

**Comment by holmesal** [comment]
Using the newest mocks, which outdate this issue. Closed! :birthday:
