### ISSUE TITLE
OSX - Cannot Copy & Paste

### ISSUE THREAD

**Issue by matthewkulp** [holmesal/hashtag#2]
Cannot paste into the 'Say Something' field.

Cannot copy messages.

Probably related to a missing Edit menu.

**Comment by holmesal** [comment]
Looks like it's related to the edit menu, detailed here:

[https://github.com/rogerwang/node-webkit/issues/1958](https://github.com/rogerwang/node-webkit/issues/1958)

Fix is to create this in-app, like so:

[https://github.com/rogerwang/node-webkit/wiki/Menu#menucreatemacbuiltinappname](https://github.com/rogerwang/node-webkit/wiki/Menu#menucreatemacbuiltinappname)

Need to build an optional script loaded, just for node-webkit apps.
